# Generated by Django 5.2.3 on 2025-07-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='updated_by',
            new_name='updated_at',
        ),
    ]
